defaultSemverRangePrefix: ""

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      "typescript": "*"
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      "@graphql-codegen/visitor-plugin-common": "*"
  "react-dev-utils@*":
    dependencies:
      typescript: "*"
      webpack: "*"
  "react-scripts@*":
    dependencies:
      eslint-config-prettier: "*"
      eslint-plugin-prettier: "*"
      prettier: "*"
  "styled-components@*":
    dependencies:
      "babel-plugin-macros": "*"
