defaultSemverRangePrefix: ""

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      "typescript": "*"
  "@firebase/auth@0.16.8":
    dependencies:
      "@firebase/app-types": "0.6.3"
      "@firebase/util": "1.3.0"
  "@firebase/database@0.11.0":
    dependencies:
      "@firebase/app": "0.6.30"
      "@firebase/app-types": "0.6.3"
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      "@graphql-codegen/visitor-plugin-common": "*"
  "react-dev-utils@*":
    dependencies:
      typescript: "*"
      webpack: "*"
  "react-scripts@*":
    dependencies:
      eslint-config-prettier: "*"
      eslint-plugin-prettier: "*"
      prettier: "*"
  "styled-components@*":
    dependencies:
      "babel-plugin-macros": "*"
