defaultSemverRangePrefix: ""

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-berry.cjs
