export * from './autogenerated/types';

import { promises as fs } from 'fs';
import path from 'path';

export const schemaLoader = async (): Promise<string> => {
  return await fs.readFile(path.join(__dirname, '..', 'graphql', 'schema.graphql'), 'utf8');
};
