export * from './autogenerated/types';
export * from './GqlProvider';

import { promises as fs } from 'fs';
import path from 'path';

export const schemaLoader = async (): Promise<string> => {
  return await fs.readFile(path.join(__dirname, 'autogenerated', 'schema.graphql'), 'utf8');
};
